### ISSUE TITLE
Won't generate short link without http*://

### ISSUE THREAD

**Issue by ItzNotABug** [WilfredAlmeida/rusly#1]
The short link isn't generated if the specified link doesn't contain a `http://` or `https://` prefix.

**Comment by WilfredAlmeida** [comment]
In the backend, the given is parsed by `url::Url`

If this fails then the URL is rejected.

To fix this, I think a regex to detect the `http*://` prefix and prepend if exists will do.

Feel free to make a PR with a solution.

Thanks for pointing it out.
